INVITION_CONFIG: BASE_DIR/config-local.yml

PRODUCT_NAME: 'Invitation Card'
PRODUCT_VERSION: '0.1.0'

SECRET_KEY: 'OVERRIDE'

DEBUG: no
SECURE_COOKIES: yes


DATABASE_NAME:      'OVERRIDE'
DATABASE_USER:      'OVERRIDE'
DATABASE_PASSWORD:  'OVERRIDE'
DATABASE_HOST:      'OVERRIDE'
DATABASE_PORT:      'OVERRIDE'

RECAPTCHA_V3_SECRET_KEY: 'OVERRIDE'
RECAPTCHA_V3_SITE_KEY: 'OVERRIDE'
RECAPTCHA_V3_SCORE: 0.5
RECAPTCHA_ENABLE: yes