# Generated by Django 3.2 on 2021-08-10 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, null=True, validators=[utils.validators.validate_mobile], verbose_name='تلفن همراه')),
                ('communicative_road', models.JSONField(blank=True, null=True, verbose_name='راه های ارتباطی')),
                ('tags', django_mysql.models.SetCharField(models.IntegerField(), blank=True, max_length=30, null=True, size=10, verbose_name='تگ')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'مخاطب',
                'verbose_name_plural': 'مخاطبین',
                'index_together': {('owner', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/', verbose_name='پیش\u200cنمایش')),
                ('schema', models.JSONField(validators=[utils.validators.validate_template], verbose_name='ساختار')),
                ('path', models.FileField(default='', upload_to='templates/', verbose_name='فایل قالب')),
            ],
            options={
                'verbose_name': 'قالب',
                'verbose_name_plural': 'قالب ها',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('title', models.CharField(default='ندارد', max_length=150, verbose_name='عنوان')),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='ارسال در تاریخ')),
                ('informations', models.JSONField(validators=[utils.validators.validate_draft7], verbose_name='اطلاعات اضافی')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.template', verbose_name='قالب')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه',
                'verbose_name_plural': 'دعوت\u200cنامه ها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('name', models.CharField(default='ندارد', max_length=20, verbose_name='نام')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیح')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب ها',
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InvitationCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='آیا حذف شده است؟')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.contact', verbose_name='مخاطب')),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.invitation', verbose_name='دعوت')),
            ],
            options={
                'verbose_name': 'کارت دعوت',
                'verbose_name_plural': 'کارت های دعوت',
                'index_together': {('invitation', 'is_sent')},
            },
        ),
    ]
