# Generated by Django 3.2 on 2021-05-14 14:34

from django.db import migrations, models
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210514_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='tags',
            field=django_mysql.models.SetCharField(models.IntegerField(), blank=True, max_length=30, null=True, size=10, verbose_name='تگ'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
