# Generated by Django 3.2 on 2021-08-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_invitationcard_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال شده'),
        ),
    ]
