# Generated by Django 3.2 on 2021-05-14 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_auto_20210514_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیح'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='ندارد', max_length=20, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='آیا حذف شده است؟'),
        ),
    ]
