# Generated by Django 3.2 on 2021-06-06 15:07

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20210514_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام قالب')),
                ('description', models.CharField(max_length=250, verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='پیش\u200cنمایش')),
                ('schema', models.JSONField(verbose_name='ساختار')),
            ],
            options={
                'abstract': False,
            },
            bases=(dashboard.models.BasicField, models.Model),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11, null=True, validators=[utils.validators.validate_mobile], verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='communicative_road',
            field=models.JSONField(verbose_name='راه های ارتباطی'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('owner', 'phone')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='contact',
            index_together={('owner', 'phone')},
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='ارسال در تاریخ')),
                ('informations', models.JSONField(verbose_name='اطلاعات اضافی')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.template', verbose_name='قالب')),
            ],
            options={
                'abstract': False,
            },
            bases=(dashboard.models.BasicField, models.Model),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
    ]
