# Generated by Django 3.2 on 2021-07-16 19:48

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210606_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'دعوت\u200cنامه', 'verbose_name_plural': 'عوت\u200cنامه ها'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'قالب', 'verbose_name_plural': 'قالب ها'},
        ),
        migrations.AddField(
            model_name='template',
            name='path',
            field=models.FileField(default='', upload_to='templates/', verbose_name='فایل قالب'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='informations',
            field=models.JSONField(validators=[utils.validators.validate_draft7], verbose_name='اطلاعات اضافی'),
        ),
        migrations.AlterField(
            model_name='template',
            name='schema',
            field=models.JSONField(validators=[utils.validators.validate_draft7], verbose_name='ساختار'),
        ),
        migrations.AlterField(
            model_name='template',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail/', verbose_name='پیش\u200cنمایش'),
        ),
    ]
