# Generated by Django 3.2 on 2021-08-05 14:16

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210717_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'دعوت\u200cنامه', 'verbose_name_plural': 'دعوت\u200cنامه ها'},
        ),
        migrations.AlterField(
            model_name='template',
            name='schema',
            field=models.JSONField(validators=[utils.validators.validate_template], verbose_name='ساختار'),
        ),
    ]
