# Generated by Django 3.2 on 2021-08-06 20:58

import dashboard.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210805_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCard',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_sent', models.BooleanField(default=False, editable=False, verbose_name='ارسال شده')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.contact', verbose_name='مخاطب')),
                ('invitation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.invitation', verbose_name='دعوت')),
            ],
            options={
                'verbose_name': 'کارت دعوت',
                'verbose_name_plural': 'کارت های دعوت',
                'index_together': {('invitation', 'is_sent')},
            },
            bases=(dashboard.models.BasicField, models.Model),
        ),
    ]
