# Generated by Django 3.2 on 2021-05-14 13:06

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=django_mysql.models.EnumField(blank=True, choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], null=True, verbose_name='جنسیت'),
        ),
    ]
