# Generated by Django 3.2 on 2021-08-05 14:16

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=django_mysql.models.EnumField(blank=True, choices=[('M', 'مذکر'), ('F', 'مونث'), ('O', 'غیره')], default='O', null=True, verbose_name='جنسیت'),
        ),
    ]
